name: Validate pnpm config

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: validate-pnpm-config-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate_pnpm_config:
    permissions:
      contents: read
    uses: fylein/workflows/.github/workflows/validate-pnpm-config.yml@master
